### ISSUE TITLE
Running without BQSR

### ISSUE THREAD

**Issue by linhbngo** [biointec/halvade#1]
Is it possible to make the BQSR requirement an option for running genomes that do not have DBSNP? It looks like I could modify the runPrintReads function to do so. Will that have any implication on the subsequent steps?

Disclaimer: I don't have bioinformatic background :)

Thanks, 

Linh

**Comment by ddcap** [comment]
Hi Linh,

Yes, it is possible to make the BQSR an option instead of a requirement, as a consequence runPrintReads doesn't need to be run as it only caclulates the new Quality scores from the BQSR file. 
My background is in computer science, but from what I have heard the BQSR step is indeed not needed, some consider it necessary while some do not. So it is up to the user. 
I added the '--skip_bqsr' option which now skips BQSR altogether and therefore you don't need to provide a database with '-D' , this is available in the latest github code. Let me know if this works.

best,
Dries

**Comment by linhbngo** [comment]
When I run the newly compiled code, the following error appears:

yarn jar HalvadeWithLibs.jar --nodes 20 --mem 120 --vcores 10 --B /user/lngo/halvade/bin.tar.gz --R /user/lngo/halvade/ref/ucsc.hg19 -I /user/lngo/halvade/in -O /user/lngo/halvade/out --skip_bqsr
[EXCEPTION] null
java.lang.NullPointerException
        at be.ugent.intec.halvade.HalvadeOptions.parseArguments(HalvadeOptions.java:632)
        at be.ugent.intec.halvade.HalvadeOptions.GetOptions(HalvadeOptions.java:131)
        at be.ugent.intec.halvade.MapReduceRunner.run(MapReduceRunner.java:70)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
        at be.ugent.intec.halvade.Halvade.runMapReduce(Halvade.java:44)
        at be.ugent.intec.halvade.Halvade.main(Halvade.java:36)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:136)

It looks like this happens due to the check for option -D in HalvadeOptions.java. I attempt to correct this by place hdfsSites into the if:

```
    if (line.hasOption("D")){
        sites = line.getOptionValue("D");
        hdfsSites = sites.split(",");
    }
```

Rerun the program, it gives me:

yarn jar HalvadeWithLibs.jar --nodes 20 --mem 120 --vcores 10 -B /user/lngo/halvade/bin.tar.gz -R /user/lngo/halvade/ref/ucsc.hg19 -I /user/lngo/halvade/in -O /user/lngo/halvade/out --skip_bqsr
[EXCEPTION] null
java.lang.NullPointerException
        at be.ugent.intec.halvade.utils.HalvadeConf.setKnownSitesOnHDFS(HalvadeConf.java:237)
        at be.ugent.intec.halvade.HalvadeOptions.GetOptions(HalvadeOptions.java:151)
        at be.ugent.intec.halvade.MapReduceRunner.run(MapReduceRunner.java:70)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
        at be.ugent.intec.halvade.Halvade.runMapReduce(Halvade.java:44)
        at be.ugent.intec.halvade.Halvade.main(Halvade.java:36)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:136)

To correct this, I have to comment out 
//            HalvadeConf.setKnownSitesOnHDFS(hConf, hdfsSites);
at line 151.

**Comment by ddcap** [comment]
I have updated the code with your suggestions, but I used an if function to skip setting the dbsnp sites when the -D option is given instead of commenting it out. Thanks.

**Comment by linhbngo** [comment]
There is a left over call to BaseRecalibrator at GATKReducer.java, line 295:

 gatk.runBaseRecalibrator(input, table, ref, newKnownSites, region);

My temporary fix (since my workflow does not require BSQR) is to comment this line out.

**Comment by ddcap** [comment]
Yes indeed, but this is the function to call BQSR, which still needs to work if BQSR is needed. In DnaGATKReducer and RnaGATKReducer which extends GATKReducer I check if the option is set and call or not call the BQSR function. 
But I found out I put the BQSR in the wrong side of the if function. Now it should work without commenting out this line. I will update it to github.

best,
Dries
