### ISSUE TITLE
Location of reference files

### ISSUE THREAD

**Issue by linhbngo** [biointec/halvade#3]
# I have the following error:

Log Type: stderr
Log Upload Time: Tue Oct 18 15:09:56 -0400 2016
Log Length: 2149
[2016/10/18 15:09:28 - DEBUG] taskId = attempt_1476193845089_0076_m_000001_0
[2016/10/18 15:09:28 - DEBUG] task = 1
[2016/10/18 15:09:28 - DEBUG] Checking for binaries...
[2016/10/18 15:09:28 - DEBUG] F E R NW NS   featureCounts
[2016/10/18 15:09:28 - DEBUG] F E R NW NS   AddOrReplaceReadGroups.jar
[2016/10/18 15:09:28 - DEBUG] F E R NW NS   MarkDuplicates.jar
[2016/10/18 15:09:28 - DEBUG] F E R NW NS   LICENSE.txt
[2016/10/18 15:09:28 - DEBUG] F E R NW NS   bowtie2
[2016/10/18 15:09:28 - DEBUG] F E R NW NS   BuildBamIndex.jar
[2016/10/18 15:09:28 - DEBUG] F E R NW NS   cushaw2
[2016/10/18 15:09:28 - DEBUG] F E R NW NS   CleanSam.jar
[2016/10/18 15:09:28 - DEBUG] F E R NW NS   bowtie2-align-s
[2016/10/18 15:09:28 - DEBUG] F E R NW NS   elprep
[2016/10/18 15:09:28 - DEBUG] F E R NW NS   STAR
[2016/10/18 15:09:28 - DEBUG] F E R NW NS   GenomeAnalysisTK.jar
[2016/10/18 15:09:28 - DEBUG] F E R NW NS   samtools
[2016/10/18 15:09:28 - DEBUG] F E R NW NS   combineVariants.sh
[2016/10/18 15:09:28 - DEBUG] F E R NW NS   bedtools
[2016/10/18 15:09:28 - DEBUG] F E R NW NS   bwa
[2016/10/18 15:09:28 - DEBUG] containers left: 31
[2016/10/18 15:09:28 - DEBUG] paired? true
[2016/10/18 15:09:28 - DEBUG] reference has been downloaded to local scratch: 2
[2016/10/18 15:09:28 - DEBUG] running command [./bin.tar.gz/bin/bwa, mem, null.fasta, -p, -t, 2, /dev/stdin]
[2016/10/18 15:09:28 - DEBUG] process ended with 1
[2016/10/18 15:09:28 - DEBUG] command not started!: [./bin.tar.gz/bin/bwa, mem, null.fasta, -p, -t, 2, /dev/stdin]
[PROCESS_ERR][2016/10/18 15:09:28] [E::bwa_idx_load_from_disk] fail to locate the index files
[2016/10/18 15:09:28 - DEBUG] SAMstream counts 0 records
[2016/10/18 15:09:28 - DEBUG] writing '@SRR998947.37501 FCD0BGCACXX:1:1101:4128:11684 length=90' to process with state 0
[2016/10/18 15:09:28 - DEBUG] 0 fastq reads processed
[2016/10/18 15:09:28 - DEBUG] starting cleanup: closing aligner
log4j:WARN No appenders could be found for logger (org.apache.hadoop.metrics2.impl.MetricsSystemImpl).
log4j:WARN Please initialize the log4j system properly.
# log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
# My configuration file looks like this:

N=30
M=160
C=4
B="/user/lngo/halvade/bin.tar.gz"
R="/user/lngo/halvade/refEMACE/v3.1/Sbicolor_313_v3.0_rename"
I="/user/lngo/halvade/inEMACE/"
O="/user/lngo/halvade/outEMACE/"
aln=1
mapmem=32
redmem=32
smt
# skip_bqsr
# I have checked and confirmed that I have all my reference files located in the directory specified at option 'R':

hdfs dfs -ls /user/lngo/halvade/refEMACE/v3.1/
Found 8 items
-rw-r--r--   2 lngo hdfs      99580 2016-10-18 10:29 /user/lngo/halvade/refEMACE/v3.1/Sbicolor_313_v3.0_rename.dict
-rw-r--r--   2 lngo hdfs  741310076 2016-10-18 10:29 /user/lngo/halvade/refEMACE/v3.1/Sbicolor_313_v3.0_rename.fasta
-rw-r--r--   2 lngo hdfs      66446 2016-10-18 10:29 /user/lngo/halvade/refEMACE/v3.1/Sbicolor_313_v3.0_rename.fasta.amb
-rw-r--r--   2 lngo hdfs      27956 2016-10-18 10:29 /user/lngo/halvade/refEMACE/v3.1/Sbicolor_313_v3.0_rename.fasta.ann
-rw-r--r--   2 lngo hdfs  732152128 2016-10-18 10:29 /user/lngo/halvade/refEMACE/v3.1/Sbicolor_313_v3.0_rename.fasta.bwt
-rw-r--r--   2 lngo hdfs      23510 2016-10-18 10:29 /user/lngo/halvade/refEMACE/v3.1/Sbicolor_313_v3.0_rename.fasta.fai
-rw-r--r--   2 lngo hdfs  183038012 2016-10-18 10:29 /user/lngo/halvade/refEMACE/v3.1/Sbicolor_313_v3.0_rename.fasta.pac
-rw-r--r--   2 lngo hdfs  366076072 2016-10-18 10:29 /user/lngo/halvade/refEMACE/v3.1/Sbicolor_313_v3.0_rename.fasta.sa
# 

Do you know what I am missing here?

Thanks, 

Linh

**Comment by ddcap** [comment]
It seems as if the download was started but somehow interrupted or not finished, could you try to delete the /tmp/halvade folder on every node and try again? 
I use a lock file to indicate the download progress of the files and have only one container per node download the files. I set a variable in it to 2 if it has been downloaded. But if you try it again and interrupt while its downloading it might still show 2, which indicates it has been downloaded, but it isn't actually there. So deleting the folder should help.  Let me know if it works, if it doesn't can you show me the log of the container where the map is being downloaded it should show a line like:
'downloading missing reference index files to local scratch'
in the stderr file.

best,
Dries

best,
Dries

**Comment by linhbngo** [comment]
Your solution fixes that error. I have created a startup script that would ssh to each datanode and clean out the tmp directory before a halvade job run. Now I encounter a different error:

All of the map tasks fail with the following error: 

# 

Log Type: syslog
Log Upload Time: Wed Oct 19 12:31:25 -0400 2016
Log Length: 6580
2016-10-19 12:29:17,644 WARN [main] org.apache.hadoop.metrics2.impl.MetricsConfig: Cannot locate configuration: tried hadoop-metrics2-maptask.properties,hadoop-metrics2.properties
2016-10-19 12:29:17,715 INFO [main] org.apache.hadoop.metrics2.impl.MetricsSystemImpl: Scheduled snapshot period at 10 second(s).
2016-10-19 12:29:17,715 INFO [main] org.apache.hadoop.metrics2.impl.MetricsSystemImpl: MapTask metrics system started
2016-10-19 12:29:17,732 INFO [main] org.apache.hadoop.mapred.YarnChild: Executing with tokens:
2016-10-19 12:29:17,732 INFO [main] org.apache.hadoop.mapred.YarnChild: Kind: TIMELINE_DELEGATION_TOKEN, Service: 10.125.8.215:8188, Ident: (owner=lngo, renewer=yarn, realUser=, issueDate=1476894529592, maxDate=1477499329592, sequenceNumber=597, masterKeyId=203)
2016-10-19 12:29:17,879 INFO [main] org.apache.hadoop.mapred.YarnChild: Kind: mapreduce.job, Service: job_1476193845089_0102, Ident: (org.apache.hadoop.mapreduce.security.token.JobTokenIdentifier@2e3967ea)
2016-10-19 12:29:17,879 INFO [main] org.apache.hadoop.mapred.YarnChild: Kind: HDFS_DELEGATION_TOKEN, Service: ha-hdfs:dsci, Ident: (HDFS_DELEGATION_TOKEN token 2758 for lngo)
2016-10-19 12:29:17,975 INFO [main] org.apache.hadoop.mapred.YarnChild: Sleeping for 0ms before retrying again. Got null now.
2016-10-19 12:29:18,176 INFO [main] org.apache.hadoop.mapred.YarnChild: mapreduce.cluster.local.dir for child: /data01/hadoop/yarn/local/usercache/lngo/appcache/application_1476193845089_0102,/data02/hadoop/yarn/local/usercache/lngo/appcache/application_1476193845089_0102,/data03/hadoop/yarn/local/usercache/lngo/appcache/application_1476193845089_0102,/data04/hadoop/yarn/local/usercache/lngo/appcache/application_1476193845089_0102,/data05/hadoop/yarn/local/usercache/lngo/appcache/application_1476193845089_0102,/data06/hadoop/yarn/local/usercache/lngo/appcache/application_1476193845089_0102,/data07/hadoop/yarn/local/usercache/lngo/appcache/application_1476193845089_0102,/data08/hadoop/yarn/local/usercache/lngo/appcache/application_1476193845089_0102,/data09/hadoop/yarn/local/usercache/lngo/appcache/application_1476193845089_0102,/data10/hadoop/yarn/local/usercache/lngo/appcache/application_1476193845089_0102,/data11/hadoop/yarn/local/usercache/lngo/appcache/application_1476193845089_0102,/data12/hadoop/yarn/local/usercache/lngo/appcache/application_1476193845089_0102
2016-10-19 12:29:18,506 INFO [main] org.apache.hadoop.conf.Configuration.deprecation: session.id is deprecated. Instead, use dfs.metrics.session-id
2016-10-19 12:29:19,093 INFO [main] org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter: File Output Committer Algorithm version is 1
2016-10-19 12:29:19,093 INFO [main] org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter: FileOutputCommitter skip cleanup _temporary folders under output directory:false, ignore cleanup failures: false
2016-10-19 12:29:19,109 INFO [main] org.apache.hadoop.mapred.Task:  Using ResourceCalculatorProcessTree : [ ]
2016-10-19 12:29:19,481 INFO [main] org.apache.hadoop.mapred.MapTask: Processing split: hdfs://dsci/user/lngo/halvade/inEMACE/halvade_29_0.fq.gz:0+7040611
2016-10-19 12:29:20,626 INFO [main] org.apache.hadoop.mapred.MapTask: (EQUATOR) 0 kvi 525860860(2103443440)
2016-10-19 12:29:20,627 INFO [main] org.apache.hadoop.mapred.MapTask: mapreduce.task.io.sort.mb: 2006
2016-10-19 12:29:20,627 INFO [main] org.apache.hadoop.mapred.MapTask: soft limit at 1472410368
2016-10-19 12:29:20,627 INFO [main] org.apache.hadoop.mapred.MapTask: bufstart = 0; bufvoid = 2103443456
2016-10-19 12:29:20,627 INFO [main] org.apache.hadoop.mapred.MapTask: kvstart = 525860860; length = 131465216
2016-10-19 12:29:20,645 INFO [main] org.apache.hadoop.mapred.MapTask: Map output collector class = org.apache.hadoop.mapred.MapTask$MapOutputBuffer
2016-10-19 12:29:20,664 INFO [main] org.apache.hadoop.io.compress.zlib.ZlibFactory: Successfully loaded & initialized native-zlib library
2016-10-19 12:29:20,664 INFO [main] org.apache.hadoop.io.compress.CodecPool: Got brand-new decompressor [.gz]
2016-10-19 12:29:20,676 INFO [main] org.apache.hadoop.conf.Configuration.deprecation: mapred.map.tasks is deprecated. Instead, use mapreduce.job.maps
2016-10-19 12:30:02,841 INFO [main] org.apache.hadoop.mapred.MapTask: Starting flush of map output
2016-10-19 12:30:02,841 INFO [main] org.apache.hadoop.mapred.MapTask: Spilling map output
2016-10-19 12:30:02,841 INFO [main] org.apache.hadoop.mapred.MapTask: bufstart = 0; bufend = 20477240; bufvoid = 2103443456
2016-10-19 12:30:02,841 INFO [main] org.apache.hadoop.mapred.MapTask: kvstart = 525860860(2103443440); kvend = 525509388(2102037552); length = 351473/131465216
2016-10-19 12:30:03,481 INFO [main] org.apache.hadoop.mapred.MapTask: Finished spill 0
2016-10-19 12:30:03,487 WARN [main] org.apache.hadoop.mapred.YarnChild: Exception running child : java.io.EOFException: Unexpected end of input stream
    at org.apache.hadoop.io.compress.DecompressorStream.decompress(DecompressorStream.java:145)
    at org.apache.hadoop.io.compress.DecompressorStream.read(DecompressorStream.java:85)
    at java.io.InputStream.read(InputStream.java:101)
    at org.apache.hadoop.util.LineReader.fillBuffer(LineReader.java:180)
    at org.apache.hadoop.util.LineReader.readDefaultLine(LineReader.java:216)
    at org.apache.hadoop.util.LineReader.readLine(LineReader.java:174)
    at org.apache.hadoop.mapreduce.lib.input.LineRecordReader.nextKeyValue(LineRecordReader.java:186)
    at org.apache.hadoop.mapred.MapTask$NewTrackingRecordReader.nextKeyValue(MapTask.java:556)
    at org.apache.hadoop.mapreduce.task.MapContextImpl.nextKeyValue(MapContextImpl.java:80)
    at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.nextKeyValue(WrappedMapper.java:91)
    at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:145)
    at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
    at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:168)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:422)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1709)

#     at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:162)

# and the stderr log shows the following:

Log Type: stderr
Log Upload Time: Wed Oct 19 12:31:25 -0400 2016
Log Length: 5215
[2016/10/19 12:29:20 - DEBUG] taskId = attempt_1476193845089_0102_m_000000_0
[2016/10/19 12:29:20 - DEBUG] task = 0
[2016/10/19 12:29:20 - DEBUG] Checking for binaries...
[2016/10/19 12:29:20 - DEBUG] F E R NW NS   GenomeAnalysisTK.jar
[2016/10/19 12:29:20 - DEBUG] F E R NW NS   MarkDuplicates.jar
[2016/10/19 12:29:20 - DEBUG] F E R NW NS   BuildBamIndex.jar
[2016/10/19 12:29:20 - DEBUG] F E R NW NS   STAR
[2016/10/19 12:29:20 - DEBUG] F E R NW NS   cushaw2
[2016/10/19 12:29:20 - DEBUG] F E R NW NS   samtools
[2016/10/19 12:29:20 - DEBUG] F E R NW NS   featureCounts
[2016/10/19 12:29:20 - DEBUG] F E R NW NS   CleanSam.jar
[2016/10/19 12:29:20 - DEBUG] F E R NW NS   bowtie2
[2016/10/19 12:29:20 - DEBUG] F E R NW NS   bwa
[2016/10/19 12:29:20 - DEBUG] F E R NW NS   LICENSE.txt
[2016/10/19 12:29:20 - DEBUG] F E R NW NS   bowtie2-align-s
[2016/10/19 12:29:20 - DEBUG] F E R NW NS   AddOrReplaceReadGroups.jar
[2016/10/19 12:29:20 - DEBUG] F E R NW NS   combineVariants.sh
[2016/10/19 12:29:20 - DEBUG] F E R NW NS   bedtools
[2016/10/19 12:29:20 - DEBUG] F E R NW NS   elprep
[2016/10/19 12:29:20 - DEBUG] containers left: 32
[2016/10/19 12:29:20 - DEBUG] paired? true
[INFO] downloading missing reference index files to local scratch
[2016/10/19 12:29:20 - DEBUG] attempting download of "/tmp/halvade/bwa_ref-m_000000_0.fasta"
[2016/10/19 12:29:23 - DEBUG] /user/lngo/halvade/refEMACE/v3.1/Sbicolor_313_v3.0_rename.fasta downloaded
[2016/10/19 12:29:23 - DEBUG] attempting download of "/tmp/halvade/bwa_ref-m_000000_0.fasta.amb"
[2016/10/19 12:29:23 - DEBUG] /user/lngo/halvade/refEMACE/v3.1/Sbicolor_313_v3.0_rename.fasta.amb downloaded
[2016/10/19 12:29:23 - DEBUG] attempting download of "/tmp/halvade/bwa_ref-m_000000_0.fasta.ann"
[2016/10/19 12:29:23 - DEBUG] /user/lngo/halvade/refEMACE/v3.1/Sbicolor_313_v3.0_rename.fasta.ann downloaded
[2016/10/19 12:29:23 - DEBUG] attempting download of "/tmp/halvade/bwa_ref-m_000000_0.fasta.bwt"
[2016/10/19 12:29:25 - DEBUG] /user/lngo/halvade/refEMACE/v3.1/Sbicolor_313_v3.0_rename.fasta.bwt downloaded
[2016/10/19 12:29:25 - DEBUG] attempting download of "/tmp/halvade/bwa_ref-m_000000_0.fasta.pac"
[2016/10/19 12:29:26 - DEBUG] /user/lngo/halvade/refEMACE/v3.1/Sbicolor_313_v3.0_rename.fasta.pac downloaded
[2016/10/19 12:29:26 - DEBUG] attempting download of "/tmp/halvade/bwa_ref-m_000000_0.fasta.sa"
[2016/10/19 12:29:28 - DEBUG] /user/lngo/halvade/refEMACE/v3.1/Sbicolor_313_v3.0_rename.fasta.sa downloaded
[2016/10/19 12:29:28 - DEBUG] attempting download of "/tmp/halvade/bwa_ref-m_000000_0.fasta.fai"
[2016/10/19 12:29:28 - DEBUG] /user/lngo/halvade/refEMACE/v3.1/Sbicolor_313_v3.0_rename.fasta.fai downloaded
[2016/10/19 12:29:28 - DEBUG] attempting download of "/tmp/halvade/bwa_ref-m_000000_0.dict"
[2016/10/19 12:29:28 - DEBUG] /user/lngo/halvade/refEMACE/v3.1/Sbicolor_313_v3.0_rename.dict downloaded
[INFO] FINISHED downloading the complete reference index to local scratch
[2016/10/19 12:29:28 - DEBUG] running command [./bin.tar.gz/bin/bwa, mem, /tmp/halvade/bwa_ref-m_000000_0.fasta, -p, -t, 2, /dev/stdin]
[PROCESS_ERR][2016/10/19 12:29:29] [M::bwa_idx_load_from_disk] read 0 ALT contigs
[2016/10/19 12:29:31 - DEBUG] 83988 fastq reads processed
[2016/10/19 12:29:31 - DEBUG] starting cleanup: closing aligner
[PROCESS_ERR][2016/10/19 12:29:31] [M::process] read 83988 sequences (7558920 bp)...
[PROCESS_ERR][2016/10/19 12:29:31] [M::process] 0 single-end sequences; 83988 paired-end sequences
[PROCESS_ERR][2016/10/19 12:29:47] [M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (7, 12616, 3, 3)
[PROCESS_ERR][2016/10/19 12:29:47] [M::mem_pestat] skip orientation FF as there are not enough pairs
[PROCESS_ERR][2016/10/19 12:29:47] [M::mem_pestat] analyzing insert size distribution for orientation FR...
[PROCESS_ERR][2016/10/19 12:29:47] [M::mem_pestat](25, 50, 75) percentile: (474, 482, 491)
[PROCESS_ERR][2016/10/19 12:29:47] [M::mem_pestat] low and high boundaries for computing mean and std.dev: (440, 525)
[PROCESS_ERR][2016/10/19 12:29:47] [M::mem_pestat] mean and std.dev: (482.23, 11.87)
[PROCESS_ERR][2016/10/19 12:29:47] [M::mem_pestat] low and high boundaries for proper pairs: (423, 542)
[PROCESS_ERR][2016/10/19 12:29:47] [M::mem_pestat] skip orientation RF as there are not enough pairs
[PROCESS_ERR][2016/10/19 12:29:47] [M::mem_pestat] skip orientation RR as there are not enough pairs
[PROCESS_ERR][2016/10/19 12:29:58] [M::mem_process_seqs] Processed 83988 reads in 53.973 CPU sec, 27.235 real sec
[PROCESS_ERR][2016/10/19 12:30:02] [main] Version: 0.7.12-r1044
[2016/10/19 12:30:02 - DEBUG] SAMstream counts 87869 records
[PROCESS_ERR][2016/10/19 12:30:02] [main] CMD: ./bin.tar.gz/bin/bwa mem -p -t 2 /tmp/halvade/bwa_ref-m_000000_0.fasta /dev/stdin
[PROCESS_ERR][2016/10/19 12:30:02] [main] Real time: 34.598 sec; CPU: 55.366 sec
[2016/10/19 12:30:02 - DEBUG] process ended with 0
[2016/10/19 12:30:02 - DEBUG] finished cleanup
[2016/10/19 12:30:02 - DEBUG] tasks started: 0
log4j:WARN No appenders could be found for logger (org.apache.hadoop.metrics2.impl.MetricsSystemImpl).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

# 

Is this a halvade issue or something related to the data itself? A search on the PROCESS_ERR messages show that these are not error messages of bwa but just normal system messages. 

Thanks, 

Linh

**Comment by ddcap** [comment]
Yes indeed, as far as I can tell the bwa mem program finishes correctly (ended with 0 means it finished correctly).  It seems to be a problem during the phase in between the map and reduce where the data is moved between all the nodes. What Hadoop version are you using? I'll try to found out more information about this error: Exception running child : java.io.EOFException: Unexpected end of input stream
This could be a problem with disk space, that the data can be written to disk anymore and so the end is cut off? You could try to compress the intermediate data, I support snappy compression for map output data with the '--snappy' option.

best,
Dries

**Comment by linhbngo** [comment]
We are running Hadoop 2.7.2 distributed through Hortonworks HDP 2.4.2. The Hadoop cluster is a decidated system with 40 256G-RAM 24x6TB-Drive nodes. The storage allocated for /tmp on each node is mounted through ~ 1TB mount from an additional local drive. Now that I have your confirmation about bwa finishing correctly, I will start investigating on the Hadoop system side and keep you updated. 

Linh

**Comment by linhbngo** [comment]
I identify the error. It turns out that I used the .gz form of fastq for the HalvadeUploaderTool. After first gunzip the data, the mapping process is now completed successfully. We have new errors, but I will open additional issues!

Thanks, 

Linh
