### ISSUE TITLE
Null Pointer exception during Halvade pass 2 RNA job

### ISSUE THREAD

**Issue by ghost** [biointec/halvade#4]
Hi,
I am trying to run RNA-seq pipeline and tried with the example dataset given in the manual. The first job completes successfully but fails immediately during second one. Below is the exception stack and logs. Please help resolve the issue. Thanks;

**syslog** 

2016-10-19 14:57:08,084 INFO [main] org.apache.hadoop.metrics2.impl.MetricsSystemImpl: Scheduled snapshot period at 10 second(s).
2016-10-19 14:57:08,085 INFO [main] org.apache.hadoop.metrics2.impl.MetricsSystemImpl: MapTask metrics system started
2016-10-19 14:57:08,104 INFO [main] org.apache.hadoop.mapred.YarnChild: Executing with tokens:
2016-10-19 14:57:08,104 INFO [main] org.apache.hadoop.mapred.YarnChild: Kind: mapreduce.job, Service: job_1470726539245_0036, Ident: (org.apache.hadoop.mapreduce.security.token.JobTokenIdentifier@6ebe8853)
2016-10-19 14:57:08,267 INFO [main] org.apache.hadoop.mapred.YarnChild: Sleeping for 0ms before retrying again. Got null now.
2016-10-19 14:57:08,819 INFO [main] org.apache.hadoop.mapred.YarnChild: mapreduce.cluster.local.dir for child: /data/hadoop/nm-local-dir/usercache/hadoopuser/appcache/application_1470726539245_0036
2016-10-19 14:57:10,227 INFO [main] org.apache.hadoop.conf.Configuration.deprecation: session.id is deprecated. Instead, use dfs.metrics.session-id
2016-10-19 14:57:11,185 INFO [main] org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter: File Output Committer Algorithm version is 1
2016-10-19 14:57:11,254 INFO [main] org.apache.hadoop.mapred.Task:  Using ResourceCalculatorProcessTree : [ ]
2016-10-19 14:57:11,734 INFO [main] org.apache.hadoop.mapred.MapTask: Processing split: hdfs://134.68.246.158:9000/user/hadoopuser/halvade-rna/in/halvade_0_1.fq.gz:0+17875086
2016-10-19 14:57:12,045 INFO [main] org.apache.hadoop.mapred.MapTask: (EQUATOR) 0 kvi 26214396(104857584)
2016-10-19 14:57:12,046 INFO [main] org.apache.hadoop.mapred.MapTask: mapreduce.task.io.sort.mb: 100
2016-10-19 14:57:12,046 INFO [main] org.apache.hadoop.mapred.MapTask: soft limit at 83886080
2016-10-19 14:57:12,046 INFO [main] org.apache.hadoop.mapred.MapTask: bufstart = 0; bufvoid = 104857600
2016-10-19 14:57:12,046 INFO [main] org.apache.hadoop.mapred.MapTask: kvstart = 26214396; length = 6553600
2016-10-19 14:57:12,100 INFO [main] org.apache.hadoop.mapred.MapTask: Map output collector class = org.apache.hadoop.mapred.MapTask$MapOutputBuffer
2016-10-19 14:57:12,135 INFO [main] org.apache.hadoop.io.compress.zlib.ZlibFactory: Successfully loaded & initialized native-zlib library
2016-10-19 14:57:12,136 INFO [main] org.apache.hadoop.io.compress.CodecPool: Got brand-new decompressor [.gz]
2016-10-19 14:57:12,257 INFO [main] org.apache.hadoop.conf.Configuration.deprecation: mapred.map.tasks is deprecated. Instead, use mapreduce.job.maps
2016-10-19 14:57:18,439 INFO [main] org.apache.hadoop.mapred.MapTask: Starting flush of map output
2016-10-19 14:57:18,544 WARN [main] org.apache.hadoop.mapred.YarnChild: Exception running child : java.lang.NullPointerException
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1010)
    at be.ugent.intec.halvade.utils.ProcessBuilderWrapper.startProcess(ProcessBuilderWrapper.java:96)
    at be.ugent.intec.halvade.tools.STARInstance.loadSharedMemoryReference(STARInstance.java:251)
    at be.ugent.intec.halvade.hadoop.mapreduce.StarAlignPassXMapper.loadReference(StarAlignPassXMapper.java:90)
    at be.ugent.intec.halvade.hadoop.mapreduce.StarAlignPassXMapper.setup(StarAlignPassXMapper.java:67)
    at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:143)
    at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
    at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
    at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)

2016-10-19 14:57:18,556 INFO [main] org.apache.hadoop.mapred.Task: Runnning cleanup for the task
2016-10-19 14:57:18,564 WARN [main] org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter: Could not delete hdfs://134.68.246.158:9000/user/hadoopuser/halvade-rna/out/halvade/_temporary/1/_temporary/attempt_1470726539245_0036_m_000012_0

**syserr**

[2016/10/19 14:57:12 - DEBUG] taskId = attempt_1470726539245_0036_m_000012_0
[2016/10/19 14:57:12 - DEBUG] Checking for binaries...
[2016/10/19 14:57:12 - DEBUG] F E R NW NS   MarkDuplicates.jar
[2016/10/19 14:57:12 - DEBUG] F E R NW NS   elprep
[2016/10/19 14:57:12 - DEBUG] F E R NW NS   featureCounts
[2016/10/19 14:57:12 - DEBUG] F E R NW NS   bowtie2-align-s
[2016/10/19 14:57:12 - DEBUG] F E R NW NS   LICENSE.txt
[2016/10/19 14:57:12 - DEBUG] F E R NW NS   bedtools
[2016/10/19 14:57:12 - DEBUG] F E R NW NS   bwa
[2016/10/19 14:57:12 - DEBUG] F E R NW NS   combineVariants.sh
[2016/10/19 14:57:12 - DEBUG] F E R NW NS   samtools
[2016/10/19 14:57:12 - DEBUG] F E R NW NS   bowtie2
[2016/10/19 14:57:12 - DEBUG] F E R NW NS   STAR
[2016/10/19 14:57:12 - DEBUG] F E R NW NS   cushaw2
[2016/10/19 14:57:12 - DEBUG] F E R NW NS   BuildBamIndex.jar
[2016/10/19 14:57:12 - DEBUG] F E R NW NS   AddOrReplaceReadGroups.jar
[2016/10/19 14:57:12 - DEBUG] F E R NW NS   CleanSam.jar
[2016/10/19 14:57:12 - DEBUG] F E R NW NS   GenomeAnalysisTK.jar
[2016/10/19 14:57:12 - DEBUG] STAR instance type: 2
[2016/10/19 14:57:12 - DEBUG] containers left: 0
[2016/10/19 14:57:12 - DEBUG] paired? true
[2016/10/19 14:57:12 - DEBUG] reference has been downloaded to local scratch: 1
[2016/10/19 14:57:12 - DEBUG] ref: null
[2016/10/19 14:57:12 - DEBUG] Started STAR
[2016/10/19 14:57:12 - DEBUG] waiting for lock...
[2016/10/19 14:57:18 - DEBUG] pass 1 reference is still loaded into shared memory, freeing first
[2016/10/19 14:57:18 - DEBUG] reference has been downloaded to local scratch: 1
[2016/10/19 14:57:18 - DEBUG] found existing ref: "/tmp/halvade/m_000014_0-star/"
[2016/10/19 14:57:18 - DEBUG] Remove ref [/tmp/halvade/m_000014_0-star/] from shared memory.
[2016/10/19 14:57:18 - DEBUG] running command [./bin.tar.gz/bin/STAR, --genomeDir, /tmp/halvade/m_000014_0-star/, --genomeLoad, Remove]
[2016/10/19 14:57:18 - DEBUG] process ended with 105
[2016/10/19 14:57:18 - DEBUG] command not started!: [./bin.tar.gz/bin/STAR, --genomeDir, /tmp/halvade/m_000014_0-star/, --genomeLoad, Remove]
[2016/10/19 14:57:18 - DEBUG] Load ref [null] to shared memory
[2016/10/19 14:57:18 - DEBUG] running command [./bin.tar.gz/bin/STAR, --genomeDir, null, --genomeLoad, LoadAndExit]
[PROCESS_ERR][2016/10/19 14:57:18] 
[PROCESS_ERR][2016/10/19 14:57:18] EXITING: Did not find the genome in memory, did not remove any genomes from shared memory
[PROCESS_ERR][2016/10/19 14:57:18] 
[PROCESS_ERR][2016/10/19 14:57:18] Oct 19 14:57:18 ...... FATAL ERROR, exiting

**Comment by ghost** [comment]
Also,

There's another kind of exception;

Error: STAR aligner exited with code 105 at be.ugent.intec.halvade.tools.STARInstance.closeAligner(STARInstance.java:175) at be.ugent.intec.halvade.hadoop.mapreduce.HalvadeMapper.cleanup(HalvadeMapper.java:35) at be.ugent.intec.halvade.hadoop.mapreduce.StarAlignPassXMapper.cleanup(StarAlignPassXMapper.java:36) at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:149) at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787) at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341) at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164) at java.security.AccessController.doPrivileged(Native Method) at javax.security.auth.Subject.doAs(Subject.java:415) at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657) at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)

I have checked the /tmp/halvade folder. All the files are present with proper permissions. I cannot figure out what's going wrong.

**Comment by ddcap** [comment]
It seems the second star genome isn't correctly found/downloaded, could you give me the options you used to run Halvade?

best,
Dries

**Comment by ghost** [comment]
# required Halvade arguments

N=20
M=48
C=6
B="/user/hadoopuser/halvade-rna/bin.tar.gz"
D="/user/hadoopuser/halvade-rna/ref/dbsnp/dbsnp_138.hg19.vcf"
R="/user/hadoopuser/halvade-rna/ref/ucsc.hg19"
S="/user/hadoopuser/halvade-rna/ref/STAR_ref/"

# Halvade Input/Output

I="/user/hadoopuser/halvade-rna/in"
O="/user/hadoopuser/halvade-rna/out"

P
rna

**Comment by ddcap** [comment]
Could you show me the stderr log of the container that actually downloads the second genome, it should contain this line:
downloading missing reference index files to local scratch

It is possible that it is a bug with the lock files, I have updated the sources to use a different lock file for the second stage, can you test it out and let me know (it is in the latest github source code).

thanks,
Dries

**Comment by ghost** [comment]
Hi Dries,

I tried executing with updated source code. The job again failed for second genome. Below is the stderr and syslog. 

#stderr

[2016/10/24 15:01:36 - DEBUG] taskId = attempt_1470726539245_0046_m_000004_0
[2016/10/24 15:01:36 - DEBUG] task = 4
[2016/10/24 15:01:36 - DEBUG] Checking for binaries...
[2016/10/24 15:01:36 - DEBUG] F E R NW NS   MarkDuplicates.jar
[2016/10/24 15:01:36 - DEBUG] F E R NW NS   elprep
[2016/10/24 15:01:36 - DEBUG] F E R NW NS   featureCounts
[2016/10/24 15:01:36 - DEBUG] F E R NW NS   bowtie2-align-s
[2016/10/24 15:01:36 - DEBUG] F E R NW NS   LICENSE.txt
[2016/10/24 15:01:36 - DEBUG] F E R NW NS   bedtools
[2016/10/24 15:01:36 - DEBUG] F E R NW NS   bwa
[2016/10/24 15:01:36 - DEBUG] F E R NW NS   combineVariants.sh
[2016/10/24 15:01:36 - DEBUG] F E R NW NS   samtools
[2016/10/24 15:01:36 - DEBUG] F E R NW NS   bowtie2
[2016/10/24 15:01:36 - DEBUG] F E R NW NS   STAR
[2016/10/24 15:01:36 - DEBUG] F E R NW NS   cushaw2
[2016/10/24 15:01:36 - DEBUG] F E R NW NS   BuildBamIndex.jar
[2016/10/24 15:01:36 - DEBUG] F E R NW NS   AddOrReplaceReadGroups.jar
[2016/10/24 15:01:36 - DEBUG] F E R NW NS   CleanSam.jar
[2016/10/24 15:01:36 - DEBUG] F E R NW NS   GenomeAnalysisTK.jar
[2016/10/24 15:01:36 - DEBUG] STAR instance type: 2
[2016/10/24 15:01:36 - DEBUG] containers left: 12
[2016/10/24 15:01:36 - DEBUG] paired? true
[2016/10/24 15:01:36 - DEBUG] reference has been downloaded to local scratch: 1
[2016/10/24 15:01:36 - DEBUG] found existing ref: "/tmp/halvade/m_000001_0-star/"
[2016/10/24 15:01:36 - DEBUG] ref: /tmp/halvade/m_000001_0-star/
[2016/10/24 15:01:36 - DEBUG] Started STAR
[2016/10/24 15:01:36 - DEBUG] pass 1 reference is still loaded into shared memory, freeing first
[2016/10/24 15:01:36 - DEBUG] reference has been downloaded to local scratch: 1
[2016/10/24 15:01:36 - DEBUG] found existing ref: "/tmp/halvade/m_000009_0-star/"
[2016/10/24 15:01:36 - DEBUG] Remove ref [/tmp/halvade/m_000009_0-star/] from shared memory.
[2016/10/24 15:01:36 - DEBUG] running command [./bin.tar.gz/bin/STAR, --genomeDir, /tmp/halvade/m_000009_0-star/, --genomeLoad, Remove]
[2016/10/24 15:01:41 - DEBUG] process ended with 0
[2016/10/24 15:01:41 - DEBUG] Load ref [/tmp/halvade/m_000001_0-star/] to shared memory
[2016/10/24 15:01:41 - DEBUG] running command [./bin.tar.gz/bin/STAR, --genomeDir, /tmp/halvade/m_000001_0-star/, --genomeLoad, LoadAndExit]
[PROCESS_ERR][2016/10/24 15:01:41] 
[PROCESS_ERR][2016/10/24 15:01:41] EXITING because of FATAL ERROR: could not open genome file /tmp/halvade/m_000001_0-star//genomeParameters.txt
[PROCESS_ERR][2016/10/24 15:01:41] SOLUTION: check that the path to genome files, specified in --genomDir is correct and the files are present, and have user read permsissions
[PROCESS_ERR][2016/10/24 15:01:41] 
[2016/10/24 15:01:41 - DEBUG] process ended with 105
[PROCESS_ERR][2016/10/24 15:01:41] Oct 24 15:01:41 ...... FATAL ERROR, exiting
[2016/10/24 15:01:52 - DEBUG] 1574999 fastq reads processed
[2016/10/24 15:01:52 - DEBUG] starting cleanup: closing aligner
[2016/10/24 15:01:53 - DEBUG] running command [./bin.tar.gz/bin/STAR, --genomeDir, /tmp/halvade/m_000001_0-star/, --outFileNamePrefix, /tmp/halvade/m_000004_0-STARout/, --readFilesIn, /tmp/halvade/reads1_m_000004_0.fastq, /tmp/halvade/reads2_m_000004_0.fastq, --runThreadN, 1, --limitIObufferSize, 30000000, --genomeLoad, LoadAndKeep, --outStd, SAM, Unsorted]
[2016/10/24 15:01:53 - DEBUG] process ended with 105
[PROCESS_ERR][2016/10/24 15:01:53] 
[PROCESS_ERR][2016/10/24 15:01:53] EXITING because of FATAL ERROR: could not open genome file /tmp/halvade/m_000001_0-star//genomeParameters.txt
[PROCESS_ERR][2016/10/24 15:01:53] SOLUTION: check that the path to genome files, specified in --genomDir is correct and the files are present, and have user read permsissions
[PROCESS_ERR][2016/10/24 15:01:53] 
[PROCESS_ERR][2016/10/24 15:01:53] Oct 24 15:01:53 ...... FATAL ERROR, exiting
[2016/10/24 15:01:53 - DEBUG] SAMstream counts 0 records

#syslog

2016-10-24 15:01:29,598 INFO [main] org.apache.hadoop.metrics2.impl.MetricsConfig: loaded properties from hadoop-metrics2.properties
2016-10-24 15:01:29,895 INFO [main] org.apache.hadoop.metrics2.impl.MetricsSystemImpl: Scheduled snapshot period at 10 second(s).
2016-10-24 15:01:29,895 INFO [main] org.apache.hadoop.metrics2.impl.MetricsSystemImpl: MapTask metrics system started
2016-10-24 15:01:29,931 INFO [main] org.apache.hadoop.mapred.YarnChild: Executing with tokens:
2016-10-24 15:01:29,931 INFO [main] org.apache.hadoop.mapred.YarnChild: Kind: mapreduce.job, Service: job_1470726539245_0046, Ident: (org.apache.hadoop.mapreduce.security.token.JobTokenIdentifier@ae854ec)
2016-10-24 15:01:30,302 INFO [main] org.apache.hadoop.mapred.YarnChild: Sleeping for 0ms before retrying again. Got null now.
2016-10-24 15:01:31,403 INFO [main] org.apache.hadoop.mapred.YarnChild: mapreduce.cluster.local.dir for child: /data/hadoop/nm-local-dir/usercache/hadoopuser/appcache/application_1470726539245_0046
2016-10-24 15:01:33,668 INFO [main] org.apache.hadoop.conf.Configuration.deprecation: session.id is deprecated. Instead, use dfs.metrics.session-id
2016-10-24 15:01:34,823 INFO [main] org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter: File Output Committer Algorithm version is 1
2016-10-24 15:01:34,888 INFO [main] org.apache.hadoop.mapred.Task:  Using ResourceCalculatorProcessTree : [ ]
2016-10-24 15:01:35,510 INFO [main] org.apache.hadoop.mapred.MapTask: Processing split: hdfs://134.68.246.158:9000/user/hadoopuser/halvade-rna/in/halvade_4_0.fq.gz:0+60073396
2016-10-24 15:01:35,875 INFO [main] org.apache.hadoop.mapred.MapTask: (EQUATOR) 0 kvi 26214396(104857584)
2016-10-24 15:01:35,875 INFO [main] org.apache.hadoop.mapred.MapTask: mapreduce.task.io.sort.mb: 100
2016-10-24 15:01:35,875 INFO [main] org.apache.hadoop.mapred.MapTask: soft limit at 83886080
2016-10-24 15:01:35,875 INFO [main] org.apache.hadoop.mapred.MapTask: bufstart = 0; bufvoid = 104857600
2016-10-24 15:01:35,875 INFO [main] org.apache.hadoop.mapred.MapTask: kvstart = 26214396; length = 6553600
2016-10-24 15:01:35,936 INFO [main] org.apache.hadoop.mapred.MapTask: Map output collector class = org.apache.hadoop.mapred.MapTask$MapOutputBuffer
2016-10-24 15:01:36,013 INFO [main] org.apache.hadoop.io.compress.zlib.ZlibFactory: Successfully loaded & initialized native-zlib library
2016-10-24 15:01:36,015 INFO [main] org.apache.hadoop.io.compress.CodecPool: Got brand-new decompressor [.gz]
2016-10-24 15:01:36,068 INFO [main] org.apache.hadoop.conf.Configuration.deprecation: mapred.map.tasks is deprecated. Instead, use mapreduce.job.maps
2016-10-24 15:01:53,610 INFO [main] org.apache.hadoop.mapred.MapTask: Starting flush of map output
2016-10-24 15:01:54,026 WARN [main] org.apache.hadoop.mapred.YarnChild: Exception running child : STAR aligner exited with code 105
    at be.ugent.intec.halvade.tools.STARInstance.closeAligner(STARInstance.java:175)
    at be.ugent.intec.halvade.hadoop.mapreduce.HalvadeMapper.cleanup(HalvadeMapper.java:36)
    at be.ugent.intec.halvade.hadoop.mapreduce.StarAlignPassXMapper.cleanup(StarAlignPassXMapper.java:36)
    at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:149)
    at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
    at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
    at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)

2016-10-24 15:01:54,045 INFO [main] org.apache.hadoop.mapred.Task: Runnning cleanup for the task
2016-10-24 15:01:54,068 WARN [main] org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter: Could not delete hdfs://134.68.246.158:9000/user/hadoopuser/halvade-rna/out/halvade/_temporary/1/_temporary/at

**Comment by ghost** [comment]
From what I understand, there are no reference files in "/tmp/halvade/m_000001_0-star/" folder because of which its failing.

**Comment by ghost** [comment]
Hi Dries,

I noticed that the hdfs folder structure looks like this;

halvade-rna/out/pass2STARGenome
-rw-r--r--   3 hadoopuser supergroup 3156902012 2016-10-24 15:00 halvade-rna/out/pass2STARGenome/Genome
-rw-r--r--   3 hadoopuser supergroup      22670 2016-10-24 15:01 halvade-rna/out/pass2STARGenome/Log.out
-rw-r--r--   3 hadoopuser supergroup 2993086112 2016-10-24 15:00 halvade-rna/out/pass2STARGenome/SA
-rw-r--r--   3 hadoopuser supergroup 1565873616 2016-10-24 15:01 halvade-rna/out/pass2STARGenome/SAindex
-rw-r--r--   3 hadoopuser supergroup        688 2016-10-24 15:00 halvade-rna/out/pass2STARGenome/chrLength.txt
-rw-r--r--   3 hadoopuser supergroup       1283 2016-10-24 14:59 halvade-rna/out/pass2STARGenome/chrName.txt
-rw-r--r--   3 hadoopuser supergroup       1971 2016-10-24 14:59 halvade-rna/out/pass2STARGenome/chrNameLength.txt
-rw-r--r--   3 hadoopuser supergroup       1017 2016-10-24 15:00 halvade-rna/out/pass2STARGenome/chrStart.txt
-rw-r--r--   3 hadoopuser supergroup        345 2016-10-24 14:59 halvade-rna/out/pass2STARGenome/genomeParameters.txt
-rw-r--r--   3 hadoopuser supergroup    2016683 2016-10-24 14:59 halvade-rna/out/pass2STARGenome/sjdbInfo.txt
-rw-r--r--   3 hadoopuser supergroup    1797645 2016-10-24 14:59 halvade-rna/out/pass2STARGenome/sjdbList.out.tab

Is the pass2 folder supposed to look  like pass2STARGenome or pass2/STARGenome?

Thanks,
Salman

**Comment by ddcap** [comment]
Yes that seems correct. The problem lies seems to be where the new genome needs to be downloaded to every node. I haven't had much opportunity to test this as I typically use a GPFS system where I don't need to redistribute the files anymore as every node has already access to the files. I'll try to figure out what goes wrong and get back to you.

best,
Dries

**Comment by ddcap** [comment]
Hi Salman,

Could you check on the node where the provided stderr log is from if there are any files in '/tmp/halvade/m_000001_0-star/' and '/tmp/halvade/m_000009_0-star/'.
Could you also send me the stderr of the map task with this line from the second job: 
'downloading missing reference index files to local scratch'.
Sorry for the inconvenience but I cant test out the program myself as our clusters are offline because of maintenance.

best,
Dries

**Comment by ghost** [comment]
Hi Dries,

I changed /tmp/halvade location to a shared location among all nodes and executed the pipeline. I got all the files in one place (shared among all) but 'm_000001_0-star' folder is still empty. Below is the stderr log

[2016/10/26 13:28:09 - DEBUG] taskId = attempt_1470726539245_0050_m_000003_1
[2016/10/26 13:28:09 - DEBUG] task = 3
[2016/10/26 13:28:09 - DEBUG] Checking for binaries...
[2016/10/26 13:28:09 - DEBUG] F E R NW NS   MarkDuplicates.jar
[2016/10/26 13:28:09 - DEBUG] F E R NW NS   elprep
[2016/10/26 13:28:09 - DEBUG] F E R NW NS   featureCounts
[2016/10/26 13:28:09 - DEBUG] F E R NW NS   bowtie2-align-s
[2016/10/26 13:28:09 - DEBUG] F E R NW NS   LICENSE.txt
[2016/10/26 13:28:09 - DEBUG] F E R NW NS   bedtools
[2016/10/26 13:28:09 - DEBUG] F E R NW NS   bwa
[2016/10/26 13:28:09 - DEBUG] F E R NW NS   combineVariants.sh
[2016/10/26 13:28:09 - DEBUG] F E R NW NS   samtools
[2016/10/26 13:28:09 - DEBUG] F E R NW NS   bowtie2
[2016/10/26 13:28:09 - DEBUG] F E R NW NS   STAR
[2016/10/26 13:28:09 - DEBUG] F E R NW NS   cushaw2
[2016/10/26 13:28:09 - DEBUG] F E R NW NS   BuildBamIndex.jar
[2016/10/26 13:28:09 - DEBUG] F E R NW NS   AddOrReplaceReadGroups.jar
[2016/10/26 13:28:09 - DEBUG] F E R NW NS   CleanSam.jar
[2016/10/26 13:28:09 - DEBUG] F E R NW NS   GenomeAnalysisTK.jar
[2016/10/26 13:28:09 - DEBUG] STAR instance type: 2
[2016/10/26 13:28:09 - DEBUG] containers left: 13
[2016/10/26 13:28:09 - DEBUG] paired? true
[2016/10/26 13:28:10 - DEBUG] reference has been downloaded to local scratch: 1
[2016/10/26 13:28:10 - DEBUG] found existing ref: "/data2/halvade_tmp/m_000000_0-star/"
[2016/10/26 13:28:10 - DEBUG] ref: /data2/halvade_tmp/m_000000_0-star/
[2016/10/26 13:28:10 - DEBUG] Started STAR
[2016/10/26 13:28:10 - DEBUG] reference has been loaded into shared memory: 2
[2016/10/26 13:28:18 - DEBUG] 1574999 fastq reads processed
[2016/10/26 13:28:18 - DEBUG] starting cleanup: closing aligner
[2016/10/26 13:28:18 - DEBUG] running command [./bin.tar.gz/bin/STAR, --genomeDir, /data2/halvade_tmp/m_000000_0-star/, --outFileNamePrefix, /data2/halvade_tmp/m_000003_1-STARout/, --readFilesIn, /data2/halvade_tmp/reads1_m_000003_1.fastq, /data2/halvade_tmp/reads2_m_000003_1.fastq, --runThreadN, 1, --limitIObufferSize, 30000000, --genomeLoad, LoadAndKeep, --outStd, SAM, Unsorted]
[PROCESS_ERR][2016/10/26 13:28:18] 
[PROCESS_ERR][2016/10/26 13:28:18] EXITING because of FATAL ERROR: could not open genome file /data2/halvade_tmp/m_000000_0-star//genomeParameters.txt
[PROCESS_ERR][2016/10/26 13:28:18] SOLUTION: check that the path to genome files, specified in --genomDir is correct and the files are present, and have user read permsissions
[PROCESS_ERR][2016/10/26 13:28:18] 
[PROCESS_ERR][2016/10/26 13:28:18] Oct 26 13:28:18 ...... FATAL ERROR, exiting
[2016/10/26 13:28:18 - DEBUG] process ended with 105
[2016/10/26 13:28:18 - DEBUG] SAMstream counts 0 records
log4j:WARN No appenders could be found for logger (org.apache.hadoop.metrics2.impl.MetricsSystemImpl).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

**Comment by ddcap** [comment]
If you are using the shared location you should use the -refdir option, then Halvade knows it doesn't need to download the files anymore. See http://halvade.readthedocs.io/en/latest/contents/options.html for more information. Also with this log I can't see what happens to the task that actually downloads the reference. Could you try to find it? It contains this line:
'downloading missing reference index files to local scratch'.

best,
Dries
